### ISSUE TITLE
altapi.net, branding

### ISSUE THREAD

**Issue by 33mhz** [neuroscr/AppDotNetAPI#7]
I'm glad to buy altapi.net if we want to begin an explanation and more documentation... A URL can provide focus.

We don't have a name for this stuff, besides the altapi for App.net. Wonder if we do want a broad name for what this would be? Is this the same as ADNFuture not having a name? My impression is ADNFuture is a group of folks who want good things, and altapi is a good thing that would expand the network so App.net is just a node. So the broader network could have a name. I'm OK with AltAPI as a name, myself. But it is pretty stodgy.

**Comment by neuroscr** [comment]
AltAPI is just a nickname.

**Comment by 33mhz** [comment]
But it could be *the* AltAPI! You're right. A name discussion would be fit for an overview, not here.
